# Generated by Django 4.1.7 on 2023-03-30 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 23, 15, 32, 468394))),
            ],
        ),
    ]
