# Generated by Django 4.1.7 on 2023-03-30 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticeapp', '0002_alter_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 23, 15, 52, 811202)),
        ),
    ]
