# Generated by Django 4.1.7 on 2023-03-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noticeapp', '0007_alter_notice_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
